### ISSUE TITLE
(dgram) client.connect is not a function

### ISSUE THREAD

**Issue by aladushkaoya** [mathhulk/minecraft-status#1]
When developing, I used your library on Windows, everything worked fine, but after I posted it on Linux, I got the error `client.connect is not a function`, I could not google anything, so I am writing here.

There my code.
![image](https://user-images.githubusercontent.com/28214961/96464496-513c1b80-1241-11eb-99b6-ac9611a9fea9.png)

There error.
![image](https://user-images.githubusercontent.com/28214961/96464709-96604d80-1241-11eb-90ac-68cf210114d0.png)

**Comment by mathhulk** [comment]
I’ll take a look into this! Thanks for the report.

**Comment by mathhulk** [comment]
I think I found the issue.

`Socket.connect` was introduced in Node.js version 12.X and does not exist in previous versions. I am assuming the Node.js version on your Linux server might be 10.X and I would advise you to update!

**Current (15.X):** https://nodejs.org/api/dgram.html#dgram_udp_datagram_sockets
**`Socket.connect` introduced (12.X):** https://nodejs.org/docs/latest-v12.x/api/dgram.html
**10.X LTS:** https://nodejs.org/docs/latest-v10.x/api/dgram.html

I will add a notice to the documentation about this. Thanks!
